services:
  voice-auth-app:
    image: voice-auth-app
    container_name: voice-auth-app
    ports:
      - "7860:7860"
    volumes:
      - ./modelscope_hub_cache:/app/modelscope_hub_cache
      - ./voice_auth_db:/app/voice_auth_db
    environment:
      - MYSQL_HOST=106.13.0.50
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=AaBb123456!
      - MYSQL_DATABASE=dcc_dbms
      - http_proxy=http://host.docker.internal:7890
      - https_proxy=http://host.docker.internal:7890
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - no_proxy=localhost,127.0.0.1
      - NO_PROXY=localhost,127.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped 