services:
  voice-auth-app:
    image: voice-auth-app
    container_name: voice-auth-app
    ports:
      - "7860:7860"
    volumes:
      - ./modelscope_hub_cache:/app/modelscope_hub_cache
      - ./voice_auth_db:/app/voice_auth_db
    environment:
      - MYSQL_HOST=106.13.0.50
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=AaBb123456!
      - MYSQL_DATABASE=dcc_dbms
    restart: unless-stopped 